### ISSUE TITLE
Compare interactions to microarray data from DA-cat mice

### ISSUE THREAD

**Issue by dzoll** [dhimmel/opcendo#1]
I would like to search for potential interaction pairs identified in "interactions" in an other database from a microarray study. The attached file is a list of genes deferentially expressed in 4 day old Dominant Active-catenin mice which exhibit upregulated Wnt signalling specifically in OPCs.  Citation: Fancy et al., 2011 Nat Neurosci, doi: 10.1038/nn.2855

raw data source: http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE19403

[ClassComparisonP4.xlsx](https://github.com/dhimmel/opcendo/files/153794/ClassComparisonP4.xlsx)

**Comment by dhimmel** [comment]
What's a good column name for the fold change in gene expression of transfected versus wild type mice? Is there a concise term to describe this experiment?

**Comment by dzoll** [comment]
DA Cat fc? As in dominant active catenin fold change

**Comment by dhimmel** [comment]
I added this dataset and reran the analysis. I didn't apply any filters, but added the fold changes to the data files for inspection.

> DA Cat fc? As in dominant active catenin fold change

Okay I named the column `DA_Cat_fold_change` or `dac_fc` for short.

## Data provenance

@dzoll provided a processed version of GSE19403 [above](#issue-137719898) named  `ClassComparisonP4.xlsx`. We didn't use this version, since it was affected by the [Excel gene-to-date bug](https://doi.org/10.1186/1471-2105-5-80). However, this Excel file was exported from an html document. GitHub did not allow @dzoll to attach this html file, but he emailed it to me. I extracted the table as a text file, available at [`download/dominant-active-catenin-DEGs.tsv`](https://github.com/dhimmel/opcendo/blob/8f20c49dbbc17767b8d5ed46f5c094b700306ce1/download/dominant-active-catenin-DEGs.tsv).

**Comment by dhimmel** [comment]
## Biology notes for myself

Olig2-Cre - Dominant Active-Catenin is a genetically engineered mouse. The effect is overexpression of Wnt target genes, but only in the OPCs. The technology is described in [DOI: 10.1101/gad.1806309](https://doi.org/10.1101/gad.1806309).
